### ISSUE TITLE
error while evaluating conditional (wtd_repo_webtatic_enabled): 'wtd_repo_webtatic_enabled' is undefined

### ISSUE THREAD

**Issue by donvipre** [while-true-do/ansible-role-repo-webtatic#3]
### Type of Report

bug

### Actual behaviour

role failes:
error while evaluating conditional (wtd_repo_webtatic_enabled): 'wtd_repo_webtatic_enabled' is undefined

### Expected behaviour

role should not use that variable anymore.

**Comment by daniel-schier** [comment]
Thanks a lot, baaad mistake from my side.
