### ISSUE TITLE
spelling issues

### ISSUE THREAD

**Issue by donvipre** [while-true-do/ansible-role-repo-webtatic#7]
### Type of Report

bug

### Actual behaviour

"installes" in meta/main.yml and README.md

### Expected behaviour

"installs"

**Comment by laurence-hubbard** [comment]
Hi I've submitted a pull request, please can I be added as assignee?

**Comment by daniel-schier** [comment]
@laurence-hubbard thanks for your first commit :+1: If you want to participate more often, we would like to see more PRs from you.
